const CUSTOM_DELETE = {
    CUSTOM_DELETE_DATA : 'CUSTOM_DELETE_DATA',
    CUSTOM_DELETE_SUCCESS : 'CUSTOM_DELETE_SUCCESS',
    CUSTOM_DELETE_ERROR : 'CUSTOM_DELETE_ERROR'
}

export default CUSTOM_DELETE;