const CUSTOM_CREATE = {
    CUSTOM_CREATE_DATA : 'CUSTOM_CREATE_DATA',
    CUSTOM_CREATE_SUCCESS : 'CUSTOM_CREATE_SUCCESS',
    CUSTOM_CREATE_ERROR : 'CUSTOM_CREATE_ERROR'
}

export default CUSTOM_CREATE