const CUSTOM_UPDATE = {
    CUSTOM_UPDATE_DATA : 'CUSTOM_UPDATE_DATA',
    CUSTOM_UPDATE_SUCCESS : 'CUSTOM_UPDATE_SUCCESS',
    CUSTOM_UPDATE_ERROR : 'CUSTOM_UPDATE_ERROR'
}

export default CUSTOM_UPDATE;