const COURSE_NAME_LIST = {
    COURSE_NAME_LIST_DATA : 'COURSE_NAME_LIST_DATA',
    COURSE_NAME_LIST_DATA_SUCCESS : 'COURSE_NAME_LIST_DATA_SUCCESS',
    COURSE_NAME_LIST_DATA_ERROR : 'COURSE_NAME_LIST_DATA_ERROR'
};

export default COURSE_NAME_LIST;