const CUSTOM_STATUS_UPDATE = {
    CUSTOM_STATUS_UPDATE_DATA: 'CUSTOM_STATUS_UPDATE_DATA',
    CUSTOM_STATUS_UPDATE_SUCCESS: 'CUSTOM_STATUS_UPDATE_SUCCESS',
    CUSTOM_STATUS_UPDATE_ERROR: 'CUSTOM_STATUS_UPDATE_ERROR'
};

export default CUSTOM_STATUS_UPDATE