const DISCOUNT_LIST = {
    DISCOUNT_LIST_DATA: 'DISCOUNT_LIST_DATA',
    DISCOUNT_LIST_SUCCESS: 'DISCOUNT_LIST_SUCCESS',
    DISCOUNT_LIST_ERROR: 'DISCOUNT_LIST_ERROR',
};

export default DISCOUNT_LIST