const SERVICE_LIST = {
    SERVICE_LIST_DATA: 'SERVICE_LIST_DATA',
    SERVICE_LIST_DATA_SUCCESS: 'SERVICE_LIST_DATA_SUCCESS',
    SERVICE_LIST_DATA_ERROR: 'SERVICE_LIST_DATA_ERROR',
};

export default SERVICE_LIST;