const WEB_DIGITAL_LIST = {
    WEB_DIGITAL_LIST_DATA: 'WEB_DIGITAL_LIST_DATA',
    WEB_DIGITAL_LIST_DATA_SUCCESS: 'WEB_DIGITAL_LIST_DATA_SUCCESS',
    WEB_DIGITAL_LIST_DATA_ERROR: 'WEB_DIGITAL_LIST_DATA_ERROR',
};

export default WEB_DIGITAL_LIST;