const WEB_SERIES_LIST = {
    WEB_SERIES_LIST_DATA: 'WEB_SERIES_LIST_DATA',
    WEB_SERIES_LIST_SUCCESS: 'WEB_SERIES_LIST_SUCCESS',
    WEB_SERIES_LIST_ERROR: 'WEB_SERIES_LIST_ERROR'
}

export default WEB_SERIES_LIST