const W_WEB_SERIES_LIST = {
    W_WEB_SERIES_LIST_DATA: 'W_WEB_SERIES_LIST_DATA',
    W_WEB_SERIES_LIST_DATA_SUCCESS: 'W_WEB_SERIES_LIST_DATA_SUCCESS',
    W_WEB_SERIES_LIST_DATA_ERROR: 'W_WEB_SERIES_LIST_DATA_ERROR',
};

export default W_WEB_SERIES_LIST;